package pojo;
// Generated 3/12/2018 06:35:10 PM by Hibernate Tools 4.3.1


import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbCasCommand generated by hbm2java
 */
@Entity
@Table(name="TB_CAS_COMMAND",schema="MANAGER_PACKAGE")
public class TbCasCommand  implements java.io.Serializable {

   


     private String idTrx;
     private String trxType;
     private Date trxDate;
     private String xmlParam;
     private String status;
     private String message;
     private Date lastModDate;
     private String xmlEnviado;
     private String lote;
     private String ip;
     private String user;
     private String stb;

    public TbCasCommand() {
        
    }

	
    public TbCasCommand(String idTrx, String trxType, Date trxDate,String xmlParam, Date lastModDate,String status,String lote,String stb,String ip) {
        this.idTrx = idTrx;
        this.trxType = trxType;
        this.trxDate = trxDate;        
        this.xmlParam = xmlParam;
        this.lastModDate = lastModDate;
        this.status = status;
        this.lote = lote;
        this.stb = stb;
        this.ip = ip;
        
    }
    public TbCasCommand(String idTrx, String trxType, Date trxDate, String xmlParam, String status, String message, Date lastModDate, String xmlEnviado) {
       this.idTrx = idTrx;
       this.trxType = trxType;
       this.trxDate = trxDate;
       this.xmlParam = xmlParam;
       this.status = status;
       this.message = message;
       this.lastModDate = lastModDate;
       this.xmlEnviado = xmlEnviado;
    }
   
    @Id 
    @Column(name="ID_TRX", unique=true, nullable=false, length=50)
    public String getIdTrx() {
        return this.idTrx;
    }
    
    public void setIdTrx(String idTrx) {
        this.idTrx = idTrx;
    }

    
    @Column(name="TRX_TYPE", nullable=false, length=10)
    public String getTrxType() {
        return this.trxType;
    }
    
    public void setTrxType(String trxType) {
        this.trxType = trxType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TRX_DATE", nullable=false, length=7)
    public Date getTrxDate() {
        return this.trxDate;
    }
    
    public void setTrxDate(Date trxDate) {
        this.trxDate = trxDate;
    }

    
    @Column(name="XML_PARAM")
    public String getXmlParam() {
        return this.xmlParam;
    }
    
    public void setXmlParam(String xmlParam) {
        this.xmlParam = xmlParam;
    }

    
    @Column(name="STATUS", nullable=false, length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="MESSAGE", length=1500)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_MOD_DATE", nullable=false, length=7)
    public Date getLastModDate() {
        return this.lastModDate;
    }
    
    public void setLastModDate(Date lastModDate) {
        this.lastModDate = lastModDate;
    }

    
    @Column(name="XML_ENVIADO")
    public String getXmlEnviado() {
        return this.xmlEnviado;
    }
    
    public void setXmlEnviado(String xmlEnviado) {
        this.xmlEnviado = xmlEnviado;
    }
    
    @Column(name="LOTE")
    public String getLote() {
        return this.lote;
    }
    
    public void setLote(String lote) {
        this.lote = lote;
    }
    
    @Column(name="IP")
    public String getIp() {
        return ip;
    }

   
    public void setIp(String ip) {
        this.ip = ip;
    }

    @Column(name="NAME_USER")
    public String getUser() {
        return user;
    }

   
    public void setUser(String user) {
        this.user = user;
    }

    @Column(name="STB")
    public String getStb() {
        return stb;
    }

   
    public void setStb(String stb) {
        this.stb = stb;
    }




}


