package pojo;
// Generated 3/12/2018 06:35:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbUserDth generated by hbm2java
 */
@Entity
@Table(name="TB_USER_DTH"
    ,schema="MANAGER_PACKAGE"
)
public class TbUserDth  implements java.io.Serializable {


     private BigDecimal idUser;
     private String firstName;
     private String lastName;
     private String userName;
     private String password;
     private Date dateCreate;

    public TbUserDth() {
    }

	
    public TbUserDth(BigDecimal idUser, String firstName, String lastName, String userName) {
        this.idUser = idUser;
        this.firstName = firstName;
        this.lastName = lastName;
        this.userName = userName;
    }
    public TbUserDth(BigDecimal idUser, String firstName, String lastName, String userName, String password, Date dateCreate) {
       this.idUser = idUser;
       this.firstName = firstName;
       this.lastName = lastName;
       this.userName = userName;
       this.password = password;
       this.dateCreate = dateCreate;
    }
   
    @Id 
    @Column(name="ID_USER", unique=true, nullable=false, precision=6)
    public BigDecimal getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(BigDecimal idUser) {
        this.idUser = idUser;
    }

    
    @Column(name="FIRST_NAME", nullable=false, length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="LAST_NAME", nullable=false, length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="USER_NAME", nullable=false, length=50)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="PASSWORD", length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CREATE", length=7)
    public Date getDateCreate() {
        return this.dateCreate;
    }
    
    public void setDateCreate(Date dateCreate) {
        this.dateCreate = dateCreate;
    }




}


